#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Org.Lucasr.TwoWayView.Sample.Resource", IsApplication=true)]

namespace Org.Lucasr.TwoWayView.Sample
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010004
			public const int twowayview_colSpan = 2130771972;
			
			// aapt resource value: 0x7f010001
			public const int twowayview_horizontalDivider = 2130771969;
			
			// aapt resource value: 0x7f010007
			public const int twowayview_layoutManager = 2130771975;
			
			// aapt resource value: 0x7f010002
			public const int twowayview_numColumns = 2130771970;
			
			// aapt resource value: 0x7f010003
			public const int twowayview_numRows = 2130771971;
			
			// aapt resource value: 0x7f010005
			public const int twowayview_rowSpan = 2130771973;
			
			// aapt resource value: 0x7f010006
			public const int twowayview_span = 2130771974;
			
			// aapt resource value: 0x7f010000
			public const int twowayview_verticalDivider = 2130771968;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Divider = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int Icon = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int monoandroidsplash = 2130837506;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f040003
			public const int TwoWayView = 2130968579;
			
			// aapt resource value: 0x7f040002
			public const int title = 2130968578;
			
			// aapt resource value: 0x7f040000
			public const int twowayview_item_click_support = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int twowayview_item_selection_support = 2130968577;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Item = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Main = 2130903041;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050001
			public const int ApplicationName = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int Hello = 2131034112;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f060000
			public const int Mono_Android_Theme_Splash = 2131099648;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] twowayview_DividerItemDecoration = new int[] {
					16843049,
					2130771968,
					2130771969};
			
			// aapt resource value: 0
			public const int twowayview_DividerItemDecoration_android_divider = 0;
			
			// aapt resource value: 2
			public const int twowayview_DividerItemDecoration_twowayview_horizontalDivider = 2;
			
			// aapt resource value: 1
			public const int twowayview_DividerItemDecoration_twowayview_verticalDivider = 1;
			
			public static int[] twowayview_GridLayoutManager = new int[] {
					2130771970,
					2130771971};
			
			// aapt resource value: 0
			public const int twowayview_GridLayoutManager_twowayview_numColumns = 0;
			
			// aapt resource value: 1
			public const int twowayview_GridLayoutManager_twowayview_numRows = 1;
			
			public static int[] twowayview_SpacingItemDecoration = new int[] {
					16843028,
					16843029};
			
			// aapt resource value: 0
			public const int twowayview_SpacingItemDecoration_android_horizontalSpacing = 0;
			
			// aapt resource value: 1
			public const int twowayview_SpacingItemDecoration_android_verticalSpacing = 1;
			
			public static int[] twowayview_SpannableGridViewChild = new int[] {
					2130771972,
					2130771973};
			
			// aapt resource value: 0
			public const int twowayview_SpannableGridViewChild_twowayview_colSpan = 0;
			
			// aapt resource value: 1
			public const int twowayview_SpannableGridViewChild_twowayview_rowSpan = 1;
			
			public static int[] twowayview_StaggeredGridViewChild = new int[] {
					2130771974};
			
			// aapt resource value: 0
			public const int twowayview_StaggeredGridViewChild_twowayview_span = 0;
			
			public static int[] twowayview_TwoWayLayoutManager = new int[] {
					16842948};
			
			// aapt resource value: 0
			public const int twowayview_TwoWayLayoutManager_android_orientation = 0;
			
			public static int[] twowayview_TwoWayView = new int[] {
					2130771975};
			
			// aapt resource value: 0
			public const int twowayview_TwoWayView_twowayview_layoutManager = 0;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
